# Generated by Django 4.0.3 on 2022-04-07 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Do not show', 'Do not show'), ('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=11)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('crossfit_coach', models.BooleanField(default=False)),
                ('yoga_coach', models.BooleanField(default=False)),
                ('combat_coach', models.BooleanField(default=False)),
                ('fitness_coach', models.BooleanField(default=False)),
                ('dance_coach', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
