# Generated by Django 4.0.3 on 2022-04-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Title')),
                ('img', models.URLField(blank=True, null=True)),
                ('vegan', models.BooleanField(default=False)),
                ('cooking_time', models.PositiveIntegerField()),
                ('prep_time', models.PositiveIntegerField()),
                ('servings', models.PositiveIntegerField()),
            ],
        ),
    ]
