# Generated by Django 4.0.3 on 2022-04-03 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_alter_recipemodel_cooking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
