# Generated by Django 4.0.3 on 2022-04-09 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_alter_recipemodel_servings_alter_recipemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='servings',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10, 'Portions must be between 0 and 10')]),
        ),
    ]
