# Generated by Django 4.0.3 on 2022-04-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_recipemodel_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='prep_time',
        ),
    ]
