# Generated by Django 4.0.3 on 2022-04-03 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_app', '0006_recipemodel_author_recipemodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='recipe_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
