# Generated by Django 4.0.3 on 2022-04-07 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=200)),
                ('h1_span', models.CharField(blank=True, max_length=20)),
                ('quote', models.CharField(blank=True, max_length=250)),
                ('facebook_URL', models.URLField(blank=True)),
                ('tweeter_URL', models.URLField(blank=True)),
                ('instagram_URL', models.URLField(blank=True)),
                ('working_time', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StarCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_owner', to='profile_app.profilemodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
