# Generated by Django 4.0.3 on 2022-04-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=200)),
                ('h1_span', models.CharField(blank=True, max_length=20)),
                ('quote', models.CharField(blank=True, max_length=250)),
                ('facebook_URL', models.URLField(blank=True)),
                ('tweeter_URL', models.URLField(blank=True)),
                ('instagram_URL', models.URLField(blank=True)),
                ('working_time', models.TextField(blank=True)),
            ],
        ),
    ]
