# Generated by Django 4.0.3 on 2022-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=50, verbose_name='Search')),
                ('type_search', models.CharField(choices=[('WORKOUT', 'Workout'), ('RECIPE', 'Recipe')], max_length=7)),
            ],
        ),
    ]
