# Generated by Django 4.0.3 on 2022-04-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
        ('main_app', '0002_starcoach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starcoach',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_owner', to='profile_app.profilemodel'),
        ),
    ]
