# Generated by Django 4.0.3 on 2022-04-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_searchmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchmodel',
            name='type_search',
        ),
    ]
