# Generated by Django 4.0.3 on 2022-04-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_recipemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeModel',
        ),
    ]
