# Generated by Django 4.0.3 on 2022-04-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileUpdatePermission',
            fields=[
            ],
            options={
                'permissions': [('owner', 'profile_app.delete_profilemodel')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth_app.gymuser',),
        ),
    ]
