# Generated by Django 4.0.3 on 2022-04-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userprofileupdatepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileUpdatePermission',
        ),
    ]
