# Generated by Django 4.0.3 on 2022-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_delete_userprofileupdatepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='email',
            field=models.EmailField(help_text='Uniq', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
