# Generated by Django 4.0.3 on 2022-04-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_gymuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
