# Generated by Django 4.0.3 on 2022-04-07 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title of workout')),
                ('type_of_workout', models.CharField(choices=[('CROSSFIT', 'Crossfit'), ('COMBAT', 'Combat'), ('FITNESS', 'Fitness'), ('DANCE', 'Dance'), ('YOGA', 'Yoga')], default='FITNESS', max_length=8)),
                ('hour', models.CharField(max_length=10, verbose_name='Starting hour')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('venue', models.CharField(max_length=50, verbose_name='Place')),
                ('img', models.URLField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('participant', models.ManyToManyField(blank=True, related_name='participants_of_event', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
                ('team', models.ManyToManyField(blank=True, related_name='team_of_event', to=settings.AUTH_USER_MODEL, verbose_name='Team')),
            ],
        ),
    ]
