# Generated by Django 4.0.3 on 2022-04-09 06:39

import django.core.validators
from django.db import migrations, models

from gym.helpers.validators import validator_name_only_alphabet_and_space


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutmodel',
            name='title',
            field=models.CharField(max_length=30, validators=[validator_name_only_alphabet_and_space, django.core.validators.MinLengthValidator(3, 'Title must contains at least 3 characters')], verbose_name='Title of workout'),
        ),
        migrations.AlterField(
            model_name='workoutmodel',
            name='venue',
            field=models.CharField(max_length=50, validators=[validator_name_only_alphabet_and_space, django.core.validators.MinLengthValidator(3, 'Venue must contains at least 3 characters')], verbose_name='Place'),
        ),
    ]
