# Generated by Django 4.0.3 on 2022-04-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
