# Generated by Django 4.0.3 on 2022-04-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0002_workoutmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutmodel',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutmodel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
