# Generated by Django 4.0.3 on 2022-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0003_workoutmodel_img_alter_workoutmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutmodel',
            name='hour',
            field=models.TextField(verbose_name='Starting hour'),
        ),
    ]
