# Generated by Django 4.0.3 on 2022-04-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0004_alter_workoutmodel_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutmodel',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workoutmodel',
            name='hour',
            field=models.CharField(max_length=10, verbose_name='Starting hour'),
        ),
    ]
